### ISSUE TITLE
Make a better formatting of x_axis labels for missfits

### ISSUE THREAD

**Issue by xjules** [equinor/webviz-ert#101]
As show here, the labels take a lot of space:
![image.png](https://images.zenhubusercontent.com/5ce25ca3b527f52e285b3d4d/1a36da77-9ef9-4b9d-b98a-fbc91ddb80f4)

We need to format it more explanatory. Also this might be point for discussion as when we are to introduce labels (see #60) the label should describe the group rather than the missfit instead.

**Comment by oysteoh** [comment]
closing - fixed
