### ISSUE TITLE
Plot Viewer - bin selector and missing prior option

### ISSUE THREAD

**Issue by eivindsm** [equinor/webviz-ert#138]
**Describe the bug**
1) For parameter plots, the text box for number of bins is not working properly. When typing into the box, users text is replaced with default. Eg when typing 5, I end up getting 7 and when typing 10, I get 70.

2) The option for adding prior-pdf is only visible for the first plot and does not affect the consecutive plots.  

**To Reproduce**
1. Type: ert vis in /project/fmu/users/eism/reek_hm/r006/ert/model
2. Select Plot Viewer, select an ensemble and more than two parameters

**Screenshots**
![plotbug](https://user-images.githubusercontent.com/41294438/111325685-33e27080-866c-11eb-857b-c6925775cd81.PNG)

**Desktop (please complete the following information):**
 - OS: RHEL7
 - chrome

**Additional context**

**Comment by xjules** [comment]
1. The number of bins should be ideally altered only via the `up/down` arrows. The `default number of bins` behavior is strange though - will look at it. 
2. Priors are visible only for the first ensemble parameters or those that have the priors information at hand. Will explore it though.

**Comment by xjules** [comment]
> 1. The number of bins should be ideally altered only via the `up/down` arrows. The `default number of bins` behavior is strange though - will look at it.

Was trying to reproduce it, but both in chrome and firefox had worked (though on the last version), ie. both typing the value and changing it by arrows worked.

> 2. Priors are visible only for the first ensemble parameters or those that have the priors information at hand. Will explore it though. 

We need to have a discussion on this as the priors are where they should be according to our thought at least.

**Comment by oysteoh** [comment]
> > 1. The number of bins should be ideally altered only via the `up/down` arrows. The `default number of bins` behavior is strange though - will look at it.
> 
> Was trying to reproduce it, but both in chrome and firefox had worked (though on the last version), ie. both typing the value and changing it by arrows worked.

It does not work by erasing the current value - only by mark and change. The problem of writing `10` and getting `70` is that `1` is prohibited and reverted back to the original "unnoticed" and then typing `10` becomes whatever was there before + `0`.

**Comment by oysteoh** [comment]
> > 1. Priors are visible only for the first ensemble parameters or those that have the priors information at hand. Will explore it though.
> 
> We need to have a discussion on this as the priors are where they should be according to our thought at least.

We'll arrange a discussion to agree on how this should be! I can confirm i see the same behavior as @xjules points out, only priors for the first ensemble parameters or those that have the priors information at hand.
