### ISSUE TITLE
Response Correlation view - timeseries for more than one ensemble not displayed

### ISSUE THREAD

**Issue by eivindsm** [equinor/webviz-ert#139]
**Describe the bug**
In Response Correlation Viewer, when selecting more than one ensemble, only responses from one ensemble is plotted in the leftmost plot, eg the one showing timeseries or responses vs indices for gen_data. 

**To Reproduce**
Open viewer and select more than one ensemble. 

**Expected behavior**
Would expect to see responses from all selected ensembles. 

**Screenshots**
![plotbug](https://user-images.githubusercontent.com/41294438/111327234-7eb0b800-866d-11eb-9435-5289d3f69283.PNG)

**Desktop (please complete the following information):**
 - RHEL 7
 - chrome

**Comment by xjules** [comment]
Can confirm that it shows only the first ensemble responses.
