### ISSUE TITLE
Response correlation view - scales out of proportions with firefox

### ISSUE THREAD

**Issue by eivindsm** [equinor/webviz-ert#143]
**Describe the bug**
The four frames in the response correlation view are way too big in firefox and I have to scroll in two directions simultaneously. It scales well with chromium. 
 
**To Reproduce**
On RGS run: webviz preferences --browser chromium-browser
Run ert vis, and select Response correlation view

**Expected behavior**
Would think it should behave as with chrome

**Screenshots**

**Desktop (please complete the following information):**
 - RHEL7
 - Firefox

**Comment by oysteoh** [comment]
We will try to reproduce

**Comment by oysteoh** [comment]
Are you @eivindsm able to run locally on any device - or just RGS? I'm not able to reproduce locally with an updated firefox version, but i know from @anders-kiaer there is bugs regarding webviz on the RGS version of firefox which is also not present in newer versions ( which currently is 78.9.0 ). Newest firefox is version 89 so we are lagging quite far behind. RGS team is in the process of upgrading. The version used now has security issues and adviced by Red Hat to be upgraded back in april. If it will fix any of our issues is yet to be known. Should we spend much time debugging this issue?

```
Red Hat Product Security has rated this update as having a security impact of **Important**.
Issued: 2021-04-26
```

**Comment by eivindsm** [comment]
I only tested on RGS. If Firefox is to be updated before webviz-ert goes public, I see no reason to spend time on this at this point.

**Comment by oysteoh** [comment]
Then i'll put this in our backlog and will have a look further down the line and see if is still present.

**Comment by frode-aarstad** [comment]
The firefox version on RGS is currently ` 91.4.0esr`
