### ISSUE TITLE
Ensemble selector not redrawing when minimize/maximize

### ISSUE THREAD

**Issue by ManInFez** [equinor/webviz-ert#154]
**Describe the bug**
When there is only one ensemble in the database, the ensemble selector will not redraw when minimising/maximising

**To Reproduce**
1. Go to 'ert/test-data/local/poly_example'
2. run `ert test_run poly.ert --enable-new-storage`
3. run `ert vis`
4. click `minimize` on ensemble selector
5. See error

**Expected behavior**
The ensemble should be centered in the selector view

Most likely due to cytoscape not redrawing when no new edges are added.

**Comment by oysteoh** [comment]
Try to reproduce. If is a bug in cytoscape - report / make an issue for them to fix.

**Comment by ManInFez** [comment]
reported to cytoscape: https://github.com/plotly/dash-cytoscape/issues/142

Could make a temp fix with a self referencing edge, but looks silly
