### ISSUE TITLE
Simplify and unify ensemble display names in views

### ISSUE THREAD

**Issue by xjules** [equinor/webviz-ert#162]
The generated names for ensembles can be really long (in some views) and also they seem to vary. We should fix this by making the names unique, unified and concise as much as possible.

An example of the issue from plot viewer:
![image.png](https://images.zenhubusercontent.com/5ce25ca3b527f52e285b3d4d/a6d73f95-0640-4351-8a95-e8a777fbc750)

**Comment by dotfloat** [comment]
Imo, the ensemble names should be generated from experiment names. Ie, `"{experiment_name} - Iter {iteration_num}"`. The date should be possible to obtain, but shouldn't be part of the name (twice).

Eg `"default - Iter 1"`.
