### ISSUE TITLE
Fix integration komodo test in order not to poke the storage first

### ISSUE THREAD

**Issue by xjules** [equinor/webviz-ert#168]
Currently the test `test_webviz_parameter_comparison` `tests/data/spe1_st/tests/test_webviz_ert.py` requires to poke the storage first (ie. via `get_ensemble_id`) in order that the gui elements are populated correctly. We should try to find out why is that and remove it.

**Comment by mortalisk** [comment]
These tests are run from komodo_releases. Currently they are copies of the tests in this repo marked with spe1. There is also an issue to merge these tests in #205

**Comment by DanSava** [comment]
#205 has been merged is this issue still relevant?

**Comment by oysteoh** [comment]
This seems still relevant as we are struggling with the test hanging on our CI suddenly.
