### ISSUE TITLE
Non date index incorrectly sorted in plot viewer

### ISSUE THREAD

**Issue by TerryHannant** [equinor/webviz-ert#193]
**Describe the bug**
When a response which has an non date index is plotted in plot viewer the index is incorrectly sorted

**To Reproduce**
1. nstall ert and webviz-ert, both `main`
2. Run a test run of snake_oil test data `ert test_run   test-data/local/snake_oil/snake_oil.ert`
3. Launch webvis `ert vis   test-data/local/snake_oil/snake_oil.ert`
4. Select `Plot Viewer` in sidebar
5. Select ensemble
6. Select parameter `SNAKE_OIL_OPR_DIFF`
7. See X axis values are in string sorted order

**Expected behavior**
The X axis should be numerically sorted

**Screenshots**
![image](https://user-images.githubusercontent.com/83143/143462679-1750f7e7-4dc2-4606-b0fc-3c9becf466ac.png)

**Comment by mortalisk** [comment]
Closing, since it seems to be fixed already.
