### ISSUE TITLE
X-axis on parameters in the plot view is not ordered correctly

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#195]

**Comment by DanSava** [comment]
I don't think there is an issue with the parameters x-axis:
There might be a small issue with the y-axis but it is not critical in my opinion.

**Side by side comparison QT plotter with Webviz-ERTside by side comparison QT plotter with Webviz-ERT**:
![Screenshot from 2021-12-08 13-49-53](https://user-images.githubusercontent.com/4508053/145203986-4b41c3ae-a353-4c0a-bfe3-70a45ffb48a2.png)

The shape of the parameter histogram seems to be correct so I am not sure what the problem would be with the x-axis of the parameters for the webviz-ert case. 

But there seems to be an issue with the x-axis for the responses in the plot view
