### ISSUE TITLE
Investigate the http communication and what is going on

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#197]
Do metrics on 
- how many calls are invoked
- size of the data transferred
- timing of request -> response
- differences between local machine / rgs node

**Comment by TerryHannant** [comment]
### Comparison of storage backends
A large part of the performance the storage api is related to the back-end used.

To quantify this the following test was run:

- The Drogon teaching project was copied to local development server as well as an RGS node (Stavanger)
- The drogon_design.ert was chosen as it has 160 realizations and 149 "records"
- The drogon_design.ert configuration and associated data was imported into both local Postgres and SQLlite dbs
- Four Storage API were run (RGS Dark storage,Dark storage,Potsgres and SQLlite).
- All local Storage APIs (and their DBs) were run on same NVMe drive to minimize IO impact (not concurrently)
- All Storage APIs were accessed via localhost (loopback address) 
- A simple standalone testbed was written to attempt to retrieve all numerical data from each Storage APIs (not in parallel) and record total request times
- Multiple runs were used to verify the timing information was consistent

#### Results

- In all cases a total of approx 29M data was retrieved
- RGS Node Dark Storage was roughly 30% slower than local Dark Storage
- In general the local Dark Storage backend was 3 to 4 times slower than Postgres and 4 to 8 slower than SQLlite
- Postgres times were slower than expected, would it expect its times to be closer to SQLlite

**Comment by TerryHannant** [comment]
After some preliminary tracing , have found two major areas which appear to unnecessarily contribute to the  total time:

## Using threadpool to parallelize loading of realizations

## Copying each data element individually

**Comment by frode-aarstad** [comment]
Just want to add some numbers I found interesting regarding serializing of pandas data frames.

```
Shape 3 rows x 1000 cols
to csv           Total time used: 0.022781494990340434   write: 0.003188028000295162     read 0.019593466990045272       size: 23662
to feather       Total time used: 0.11940125799446832    write: 0.056826970001566224     read 0.0625742879929021         size: 446747
to parquet       Total time used: 0.15567906500655226    write: 0.05812626300030388      read 0.09755280200624838        size: 696720

Shape 2000 rows x 10000 cols
to csv           Total time used: 9.540638055012096      write: 6.415710412009503        read 3.124927643002593          size: 77962454
to feather       Total time used: 1.2351486589905107     write: 0.5232189779926557       read 0.711929680997855          size: 73827507
to parquet       Total time used: 2.85003465799673       write: 1.2404046899901005       read 1.6096299680066295         size: 66760938
```

So it might be interesting to optimize how we organize the data

**Comment by oysteoh** [comment]
Closing this as we have made issues of the findings.
