### ISSUE TITLE
Investigating opendap

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#198]
webviz has already ran into issue with memory problem and performance problems on the client. They have "solved" it by using pyarrow along with interpolation-algorithms server side to do it more efficient.

We have to do something as well to minimize the data sent towards the client - and we should look into an other technology hosting the api - maybe opendap ( with pydap )?

**Comment by mortalisk** [comment]
Is this still relevant?

**Comment by oysteoh** [comment]
Not relevant anymore - closing
