### ISSUE TITLE
Make spe1 tests in komodo-releases run the tests in this repo markes with spe1

### ISSUE THREAD

**Issue by mortalisk** [equinor/webviz-ert#205]
There are some tests in komodo_releases in jenkins/komodo_releases/spe1_st/tests

These tests also exist in this repo. They should be merged. And the code should clone this repo and run the correct version of the tests from here.

**Comment by mortalisk** [comment]
Poking @xjules

**Comment by DanSava** [comment]
Spe1_st test was removed from komodo_releases and in place the webviz-ert unit-tests are running for each release.
