### ISSUE TITLE
Redrawing responses takes time

### ISSUE THREAD

**Issue by DanSava** [equinor/webviz-ert#209]
**Issue**
Every time a new response is selected or deselected all previously drawn responses are resized and redrawn. 

**Describe the solution you'd like**
Investigate if it is possible to reduce drawing time for responses, also if possible just resize previous drawn responses and avoid redrawing plots when possible.

**Comment by DanSava** [comment]
Did some testing for pure draw times of dash and plotly using the following example:

``` python
import time

import dash
from dash import html, dcc
from dash.dependencies import Output, Input, State
import pandas as pd
import plotly.graph_objs as go
import random
import numpy as np
import plotly.express as px

# create app
app = dash.Dash(
    __name__,
    external_stylesheets=[
        "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"
    ],
)

fig = go.Figure()
reals = 1000
nu_vals = 100


app.layout = html.Div(
    className="section",
    id="main_layout",
    children=[
        html.Button(
            id="enter-button1",
            className="button is-large is-outlined",
            children=["Test Scattergl"],
        ),
        dcc.Link("ccc", id="id_link", href="/test"),
        html.Label(id="lbl_2", children=["test"]),
        html.P(""),
        html.Button(
            id="enter-button2",
            className="button is-large is-outlined",
            children=["Test plotly express line"],
        ),
        dcc.Link("ccc", id="id_link2", href="/test"),
        html.Label(id="lbl_1", children=["test"]),
    ],
)


@app.callback(
    [Output("id_link", "children"), Output("lbl_2", "children")],
    [Input("enter-button1", "n_clicks")],
    [State("id_link", "children")],
)
def button_1(n_clicks, _):
    if n_clicks is not None:
        fig.data = []
        start_time = time.time()
        for i in range(reals):
            fig.add_trace(
                go.Scattergl(
                    x=list(range(nu_vals)),
                    y=[random.randint(0, nu_vals) for _ in range(nu_vals)],
                )
            )
        fig_gen_time = time.time() - start_time
        return [dcc.Graph(figure=fig)], [
            f"Reals: {reals} Values: {nu_vals} --- Total time = {fig_gen_time}"
        ]
    return [dcc.Graph(figure=fig)], [""]


@app.callback(
    [Output("id_link2", "children"), Output("lbl_1", "children")],
    [Input("enter-button2", "n_clicks")],
    [State("id_link2", "children")],
)
def button_2(n_clicks, _):
    if n_clicks is not None:
        start_time = time.time()
        matrices = np.random.rand(nu_vals, reals)

        data_df = pd.DataFrame(
            matrices,
            columns=[f"Realisation {i}" for i in range(reals)],
        )
        data_gen_time = time.time() - start_time
        start_time = time.time()
        fig = px.line(data_df)
        fig_gen_time = time.time() - start_time
        return [dcc.Graph(figure=fig)], [
            f"Reals: {reals} Values: {nu_vals} --- data gen time {data_gen_time} seconds --- fig gen time {fig_gen_time} seconds --- total = {data_gen_time + fig_gen_time}"
        ]

    return [dcc.Graph(figure=go.Figure())], [""]


if __name__ == "__main__":
    app.run_server(debug=True)
```

The test case represents 1000 realisations with 100 data values for each realisation, nothing too big, I encourage everyone to play with these values and get a feel of how "fast" a barebones dash plot drawing can be, (SPOILER ALERT it is not very fast)

**Comment by markusdregi** [comment]
That is good to know @DanSava 👍🏻

**Comment by TerryHannant** [comment]
When I run that code I get this warning

>DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  >Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = >frame.copy()`

So it would seem something is not quite set up properly?

**Comment by DanSava** [comment]
> When I run that code I get this warning
> 
> > DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  >Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = >frame.copy()`
> 
> So it would seem something is not quite set up properly?

As far as I can tell that warning is coming from some `plotly express line` internal shenanigans. So basically the conclusion is to avoid using plotly.express.line to draw massive data-frames it is not really optimized at the moment. 

Anyway that example is there to showcase there are multiple ways of rendering a simple plot using dash and plotly.
Webviz-ert is using the `add_trace` approach where you build a figure object and then add "traces"(basically lines f(x)=y) to it.

I am sure there are other ways of rendering plots using dash and plotly some might be even better than what we have so far but this example is here to show that we won't be able to shave a 2.5 seconds delay due to rendering for a case that is 1000 reals with 100 values. 

If we are talking about 1000 reals with 10000 values then we can expect something like 30 seconds of rendering time :face_with_spiral_eyes: .

**Comment by TerryHannant** [comment]
The use of lists in your example does have a large effect on perfomance, 
In the ScaaterGL example if the lines

`            x=list(range(nu_vals)),
             y=[random.randint(0, nu_vals) for _ in range(nu_vals)],
`
are replaced with (note X can be skipped altogether since it defaults to simple range)
`y = np.random.randn(nu_vals)`

Then on  RGS the total time drops from previous time of 2s to a much better 0.2s
