### ISSUE TITLE
Get list of response with observation from storage. 

### ISSUE THREAD

**Issue by DanSava** [equinor/webviz-ert#214]
**Is your feature request related to a problem? Please describe.**
For the Plot Viewer page when trying to sort and show only responses that have observations, webviz will make one HTTP call to

```
/ensembles/{ensemble_id}/records/{record_name}/observations?realization_index=0
```
to check if the response has observations in order to filter the responses list. 

For cases with a lot of responses, 100 + responses will result in 100 + HTTP calls per ensemble. 

The Observation Analyzer page has the same issue when selecting an ensemble and listing the responses with observations.

**Comment by frode-aarstad** [comment]
Have verified that this works side by side with the old lazy loading of observations. (ie for ert-storage)
