### ISSUE TITLE
Clear cache / recover from failure in selected data

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#229]
User testing with datasets new / unknown to us sometimes leads to errors in webviz-ert - typically a key is selected which causing an exception. The user then gets redirected immediately to the front-page. Going back to the page in question the key causing the failure is already selected and naturally causing the same exception again and the user is thrown back to the front-page without the possibility of deselecting the key. 

Solving this issue i guess is 2 part
- Handling what is actually causing the exception in webviz-ert  
- Always recover from an exception and / or notify the user of the event with the possibility to at least remove or do something with the faulty data instead of being forced to close and then launch `ert vis ..... .ert` again.

**Comment by oysteoh** [comment]
User testing immediately hit this issue as they provoked some kind of error but was unable to recover as they just was thrown back to front page. 

We should communicate what went wrong in order to get bug-reports from our users on this and also provide the users with the possibility to recover from the failure by de-selecting the key in issue

**Comment by DanSava** [comment]
Is there any issue when selecting the key `WBHP:A1`in the QT GUI ?

**Comment by oysteoh** [comment]
> Is there any issue when selecting the key `WBHP:A1`in the QT GUI ?

No - sorry. The exception was what was discovered a long time ago. That one is fixed but the issue with redirect and missing information to the user still remains. I clicked around a bit but did not discover any issues with the keys i selected, but there is a lot! I will do some more and try to provoke some errors which we could have a look at.

**Comment by frode-aarstad** [comment]
Which dataset can I use to reproduce this problem ?

**Comment by oysteoh** [comment]
currently on a case with restricted access, i will have a look at the Drogon case and see if i can reproduce there and report back in this issue if i figure out something.

**Comment by oysteoh** [comment]
with the drogon-case, bleeding enabled - the bug with redirect to main page can be reproduced like this

- `ert vis drogon_ahm_noseis.ert`
- Click on the `Observation Analyzer`
- Select `pred_op5`
- Select i.e `WWCT:A1` 

You will be redirected to the main page. The issue with us not being able to recover from the error seems to have been fixed, now it is possible to go back and the faulty key is not longer selected. Not sure if this applies everywhere, but i cannot at least reproduce it. 

So what is left in this issue then is probably just give an error msg stating data is not available for this key in this ensemble  when it is selected and then just stay on the same page ?
