### ISSUE TITLE
"experimental-mode" feature-flag to hide pages

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#249]
We should have the possibility to provide pages to early testing by our expert users. These pages should be "hidden" behind a feature flag when starting `ert vis`

**Comment by frode-aarstad** [comment]
Do we currently have any pages we want to hide behind this flag?

**Comment by oysteoh** [comment]
I think this might be answered on tuesday, or at least discussed. The wish came from those who had tried webviz-ert and thought the pages was a bit to complicated for normal users.
