### ISSUE TITLE
Plot viewer should be split in two

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#268]
One for "responses" and one for "parameters", or at least it is a bit "messy" having distributions, summary data etc in a big lump. We would rather have one summary data, and only be able to select one response, now it needs two clicks to change the view.

We decided during the planning to make an horizontal separation between the plots.

**Comment by valentin-krasontovitsch** [comment]
just so I understand this correctly - horizontal separation means something like
```
RESP-PLOT    RESP-PLOT
RESP-PLOT

------ SEPARATOR -----

PARAM-PLOT  PARAM-PLOT
```

is that correct?
