### ISSUE TITLE
Create videos demoing webviz-ert and it's features

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#269]

**Comment by DanSava** [comment]
Video tutorial for startup and the plot viewer

https://user-images.githubusercontent.com/4508053/178277290-b0905884-5ee3-4f40-b8cf-a49ba7791393.mp4


Gif for startup and the plot viewer

![webviz-ert_preview](https://user-images.githubusercontent.com/4508053/178277471-3ea20ef8-c3f2-4412-b3e0-310134a6664b.gif)

**Comment by DanSava** [comment]
Full tutorial video:


https://user-images.githubusercontent.com/4508053/178432171-2f0f51ed-d4fd-4228-9ada-13ec5093729b.mp4

Gifs:

![full_tutorial_p_1](https://user-images.githubusercontent.com/4508053/178432250-20c5d093-9920-4eb8-af50-d588449b74b0.gif)

![full_tutorial_p_2](https://user-images.githubusercontent.com/4508053/178432300-fd3e9dd3-ed27-4597-b08b-9df0e28dc0fc.gif)

![full_tutorial_p_3](https://user-images.githubusercontent.com/4508053/178432314-10193b5c-0130-471d-bba6-1aab1117f180.gif)

**Comment by DanSava** [comment]
Up for discussion if this is enough or if we also want a video with voice-over (computer-generated voice)?

Making a semi-decent version with voiceover requires a bit more time spent acquiring additional video-editing skills for me at least. So we need to keep that in mind.

**Comment by oysteoh** [comment]
I think this looks very good. From my point of view voice over should not be necessary. 👍 👍 👍 👍

**Comment by oysteoh** [comment]
how are we making this available for our users? Should we upload to the docs and have it there?

**Comment by DanSava** [comment]
What do we want to expose to the users, the video the gifs? or both?

I can try to add the gifs at least to the GitHub page and see how they look

**Comment by valentin-krasontovitsch** [comment]
first of all i really like the videos, good job Dan!

we could do it like the cool kids and upload the videos to youtube, and link to them? if that's permissible by our licenses and acceptable according to policy?

I'm sorry, i'm probably late to the discussion, but I was wondering: how do we expect users to "consume" these videos? do they use them for inspiration as new webviz-ert users, or is it a refresher to show all available functions also for existing users? should they try to reproduce the video, in a side by side setting?

i'm not a user, so this probably doesn't mean much, and is just my personal opinion - if we skip the voice over, some captions would definitely help to explain what i'm looking at.

we can of course (probably you've already discussed / planned this) show the videos to some users, and get direct feedback from them.

**Comment by hnformentin** [comment]
Very nice job @DanSava ! I think that the font size is too small, so I suggest to increase it in the next recordings.

**Comment by oysteoh** [comment]
> we could do it like the cool kids and upload the videos to youtube, and link to them? if that's permissible by our licenses and acceptable according to policy?

I don't see the reason of uploading to youtube - what should be the benefit of that? I think having it as links on github and/or fmu-docs should be enough. And of-course the videos needs to be maintained as we change layout and functionality on the pages. Thus - it should be as low effort from our side as possible - but also give the users a glance of all the functionality. The videos along with the guided tour functionality i think is "good enough". 

> I'm sorry, i'm probably late to the discussion, but I was wondering: how do we expect users to "consume" these videos? do they use them for inspiration as new webviz-ert users, or is it a refresher to show all available functions also for existing users? should they try to reproduce the video, in a side by side setting?

From my point of view - this is only instructions / visualize how to use it for new and existing users. They are not to reproduce the video

> i'm not a user, so this probably doesn't mean much, and is just my personal opinion - if we skip the voice over, some captions would definitely help to explain what i'm looking at.

I think the users perfectly well know what they are looking at. What we try to give them now is out-of-the-box visualizations they normally have to do on their own.
 
> we can of course (probably you've already discussed / planned this) show the videos to some users, and get direct feedback from them.

That is a good idea and something we should do !

**Comment by valentin-krasontovitsch** [comment]
oh benefit of youtube is just availability - i don't know how well github can deal with videos, besides gifs. if it's possible to host it on github or our internal docs, and it has a convenient user interface, then we can of course just use those : )

thanks for clearing up the other points!

**Comment by DanSava** [comment]
Splitting the gif into 5 parts:

* **Startup**
![startup](https://user-images.githubusercontent.com/4508053/186850915-4b53c4fb-273d-4c15-961c-299966c3232c.gif)

* **Plot viewer**
![plot_viewer](https://user-images.githubusercontent.com/4508053/186850936-38a13f16-f795-4691-8455-fc12f8372d8e.gif)

* **Observation Analyzer**
![observation_analyzer](https://user-images.githubusercontent.com/4508053/186850964-68b137eb-17c4-4bf9-9436-81c8c86e5956.gif)


* **Parameter comparison**
![parameter_comparison](https://user-images.githubusercontent.com/4508053/186851000-e5b750e1-d7ae-4da4-a612-b6c3740f5698.gif)


* **Response Correlation**
![response_correlation](https://user-images.githubusercontent.com/4508053/186851026-df2085fd-5c35-42a6-a87e-c1890a963254.gif)
