### ISSUE TITLE
Refactor: Make test data and tests less brittle and moist (DRYer)

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/webviz-ert#278]
Working with the test code, and the test data, I see several things that give me pause:

- constant literal strings that are repeated within and across files (e.g. ensemble or response names in test data and in test scripts)
- constant literal strings that are repeated across code and tests (e.g. class names of certain elements)

the first point is in my personal opinion a violation of DRY - each string literal should be defined as a constant, and that constant then referenced both in the rest of the file and in other files.

the latter point makes the tests brittle, I think - if we change the class names in the code, tests will break, perhaps without our intending for the tests to break (I'm thinking of those cases where the class name is simply used to find a certain element). I think here, too, we should define the class names as constants in the source (not testing) code, and then import them in our tests and use them to refer to / find the elements we need in testing.

Since I'm rather new to the project, probably somebody should weigh in on this and comment if it's actually worthwile / sensible to attack this problem (is it really a problem?), and of course the solution is up for discussion as well : )

**Comment by hnformentin** [comment]
Good point! I think this can be discussed in the standup. In general it makes easier to me to understand when we add the name of the variables/classes that we identify the problem.
