### ISSUE TITLE
Revert experimental state 

### ISSUE THREAD

**Issue by DanSava** [equinor/webviz-ert#281]
**Issue**

In `webviz_ert/assets/webviz-config.yml` for `ParameterComparison` and `ResponseCorrelation` set `experimental` to `False`

We have been a bit trigger-happy with the use of the newly implemented ability to set a page as `experimental`  and this is what happened for  `ParameterComparison` and `ResponseCorrelation` but once a page is set as experimental it will not be displayed by default and maybe we need a bit more time to discuss which of the pages should actually be experimental.

**Comment by hnformentin** [comment]
The only use I could think about was to make tests on the user interface, where `id_view` could be useful to identify the elements. Nevertheless, this seems not be needed, as `id` would cover the purpose.

![Image](https://user-images.githubusercontent.com/62240435/174557378-8ead7252-fe94-472c-bdca-315066a2cb91.png)

**Comment by oysteoh** [comment]
I did not understand what you meant here @hnformentin . The issue here is - as i understand it - only to make the two pages now hidden when running `ert vis ***.ert --experimental` not hidden anymore as they should not be experimental. The functionality should stay as this will be used later.

**Comment by hnformentin** [comment]
Sorry @oysteoh , I wanted to comment this on another issue. It makes no sense here indeed. My bad.

**Comment by oysteoh** [comment]
Then i understand - no problem 👍 👍

**Comment by hnformentin** [comment]
Now @oysteoh , regarding this issue itself 🤣 , we aim to: 
- Revert the ability to set a page as experimental, or 
- Display pages `experimental=True` labelled with `beta`, in line with the issue #248 ?

**Comment by oysteoh** [comment]
We just want the pages now defined as `experimental` not to be `experimental`. They could be labelled `beta` with the functionality for this to be implemented in #248
