### ISSUE TITLE
Discussion: caching vs data simplification for bigger datasets

### ISSUE THREAD

**Issue by xjules** [equinor/webviz-ert#29]
Was running one iteration on `snake_oil` example and interaction with plots becomes unbearable slow. 
Just selecting a new response (ie. populating the list box and selecting the response) takes several seconds. I know that we decided not to focus on the optimization issue yet, but still we should have it noted somewhere at least :)
![image](https://user-images.githubusercontent.com/6409506/96579498-403de980-12d7-11eb-93fb-d59df3a55c1d.png)

**Comment by xjules** [comment]
This should be resolved partly at least by enabling webgl support here https://github.com/equinor/ertviz/commit/8014e3bd6cb340cccecd9a422d50b4fa4867d56a

**Comment by oysteoh** [comment]
closing - not relevant anymore
