### ISSUE TITLE
Response correlation viewer - New selector

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#300]
We decided to make a new selector which visualizes all observations in the selected responses - something like this. The selected responses should be assigned a color when selected and the observations with the same color plotted along one ( or two depending on unit ) x-axis together with the rest of the selected responses. It should be possible to select multiple observations across the different  responses - but we should restrict to some limit which makes sense to avoid extensive load times.

![Image from iOS](https://user-images.githubusercontent.com/4184190/174234632-24f96548-f523-4106-a28e-8de09a6d61f3.jpg)

**Comment by DanSava** [comment]
Had a chat with @hnformentin and decided to merge https://github.com/equinor/webviz-ert/pull/332 even though the functionality has some bugs that need to be addressed, but I will be going on holiday for 3 weeks so I don't really want to leave the work on hold while I am away. 

I will be adding a few issues with the what I consider bugs that still needs to be addressed

**Comment by valentin-krasontovitsch** [comment]
reverted #332 in 1d89601b56c2bf7fab0694283ae71bd

**Comment by valentin-krasontovitsch** [comment]
After discussing the recently merged selector, we have decided to take a more gradual approach with smaller steps to resolve this issue.

The steps are:

- make a callback that keeps track of the active ensemble and takes as input 
  * clicking on the heatmap
- introduce a container for a selector view element with a selectable list of indexes (discrete data!) for currently active response and ensemble, with search field (just like response and parameter thingy)
- make a callback that keeps track of the selected indexes (do not hijack xindex callback!) for each ensemble and response
 * updated upon using selector view element
- make a callback that updates the selector view element according to which response and which ensemble is selected, which takes as input 
  * selecting an ensemble,
  * selecting a response, and 
  * clicking on the heatmap
and takes as state
  * selected indexes

  it should display the selector with all available indexes and none chosen as soon as
  * an ensemble and
  * a response are chosen
- have a checkbox to only display indexes that have observations
- consolidate chosen indexes with currently existing xindex, and their behaviour for scatterplot, and tornadoplot as well as heatmap
- ???
- finally: make it a graph : D
