### ISSUE TITLE
Response correlation viewer - First observation should be the initial selection

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#301]
![feedback2](https://user-images.githubusercontent.com/4184190/174232954-a4219af9-75c5-4d9b-9fab-2c12ec550904.png)

**Comment by hnformentin** [comment]
Should we also apply that to `Plot Viewer`?
<img width="996" alt="Screenshot 2022-07-05 at 08 19 03" src="https://user-images.githubusercontent.com/62240435/177263612-b104f443-f372-4c93-85b1-472eebeb8748.png">

<img width="614" alt="Screenshot 2022-07-05 at 08 28 37" src="https://user-images.githubusercontent.com/62240435/177263641-fd2068f2-8ea2-4aa0-919a-0cc49a4e6d96.png">

**Comment by oysteoh** [comment]
No - it should only apply to the response correlation viewer where you select points where the selected point will change the data in the corresponding charts. The point with the first observation should be choosen as default since that is usually the first point of interest to look at .

**Comment by oysteoh** [comment]
Had a discussion with @hnformentin and decided not to change the area of the graph, only select the first observation. I.e - move the dotted line on to the first observation. Not sure if we should also then "discard" / "zoom" in on the chart and remove the data previous to this point. This should be merged to bleeding and then discussed with @howardovic before closing this issue.
