### ISSUE TITLE
Response correlation viewer - Change layout of charts

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#303]
Change layout on the charts from 4x1 -> 2x2 to make it more easy to see what is going on

(*) Image also shows wanted functionality to hide selectors is sketched in this picture - we have this and should just be communicated to the user. 

![feedback4](https://user-images.githubusercontent.com/4184190/174232958-cb36fdd3-56e4-4eff-8ee6-9c86e5a748e2.png)

**Comment by hnformentin** [comment]
To make sure I understand, `layout of the charts` refers to the four plots we have below the selectors of response and parameters. So we want to have the response plots in one line and the tornado and heatmap plots on another line. Is it correct?

**Comment by oysteoh** [comment]
it is the four yes as you say - linechart and scatter plot side by side - and then the tornado and heatmap below. He just wants to have some more space and bigger charts to look at.
