### ISSUE TITLE
Problem with Response selection

### ISSUE THREAD

**Issue by frode-aarstad** [equinor/webviz-ert#315]
When using the response selection dialog the first response selected is put in the drop down list and not in the field under the response list. Note the drop down is not visible in the screenshot. 

How to reproduce.
- open plot viewer
- select a ensemble
- select a random response

Expect:
The response should be in the list below the response list (empty in the attached image)

Perhaps related to recent changes by  @valentin-krasontovitsch 

![Image](https://user-images.githubusercontent.com/30144033/178723966-951211fc-61b3-4ed9-9f3e-aae53cb42c71.png)

**Comment by valentin-krasontovitsch** [comment]
cannot reproduce either : (

i'm also sadly not sure what you mean by drop down or not drop down - i never used that functionality i suppose.

> the parameters selector is initially a dropdown

do you mean this thingy here should not have a little arrow pointing downwards?

![dropdown](https://user-images.githubusercontent.com/15932677/178961171-d0dd4b59-959b-41bd-89c0-d029c4cb6949.png)

note that this screenshot is taken with a checkout of webviz-ert at commit db68325cdbd which is just before my redesign of the search boxes changes were merged

Frode, which browser are you using? and just to double check - you're seeing this on current main (cdb30319d2d9a)?

**Comment by frode-aarstad** [comment]
I am not seeing this anymore. So closing this for now.
