### ISSUE TITLE
Plot Viewer: Transform Buttons into icons, and reposition

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/webviz-ert#333]
Cf. [a discussion in the PR for rearranging the input fields](https://github.com/equinor/webviz-ert/pull/260#issuecomment-1174038630) - we are considering changing the buttons on the plot viewer for refreshing and collapsing / expanding the selectors into icons, and placing the icons somewhere where it's clearer that they are acting on all three input fields.

We have [requested that an icon component be implemented in webviz-core-components](https://github.com/equinor/webviz-core-components/issues/224), and this issue is blocked by that one (but that one should be done soon).

I am not sure where the icons should be placed - perhaps in some corner? My css-foo, in my experience, is sadly not very good with this, but perhaps a css wizard will come along and graciously pick up the task : )

The idea of hacking into dash or somehow hacking the webviz stack to inject javascript / css was shortly explored, but abandoned as too hacky.

I also thought about placing the icons in question in the sidebar for icons (currently upper right corner), but this turns out to not be the best idea, as

a) those icons become transparent unless the plugin is in hover state, and we might want our icons to be prominent at all times, and
b) there is a redesign well under way that will relocate the icon bar and limit the space available for any custom icons one might want to add there

**Comment by valentin-krasontovitsch** [comment]
the [component in question has been implemented](https://github.com/equinor/webviz-core-components/pull/227)! woopie! we can start playing with this, but we still have to wait for a new release of webviz-core-components to be cut.

**Comment by sondreso** [comment]
Given that the webviz framework is deprecated, we will not priorities this effort.
