### ISSUE TITLE
Response Correlation Viewer: Response overview plot for response with observations doesn't survive reload

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/webviz-ert#337]
**Describe the bug**
The response overview plot does not survive reloads when a response with observations is selected and active.

**To Reproduce**
1. Open up webviz-ert with data that containts at least two ensembles (e.g. in `ert`, `test-data/local/snake_oil`)
2. Navigate to the response correlation viewer
3. Choose an ensemble, and a response with observations (use tickbox to filter responses!)
4. Refresh / reload the page using your browser
5. The response overview plot, previously drawn, now remains blank

**Expected behavior**
The response overview plot is redrawn, like before the refresh

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 "jammy"
 - Browser: Google Chrome 102.0.5005.115

**Comment by DanSava** [comment]
Cased by 
``` python
                if corr_xindex[selected_response] == 0 and isinstance(
                    x_axis, (pd.Index, list)
                ):
                    corr_xindex[selected_response] = _update_corr_index_dict(
                        x_axis, response.observations[0].data_df()
                    )
```

fix  replace above with

``` python 
                if not corr_xindex:
                    corr_xindex[selected_response] = _update_corr_index_dict(
                        x_axis, response.observations[0].data_df()
                    )

```

**Comment by valentin-krasontovitsch** [comment]
Haha nice : )

and thanks for the fix! Indeed the check for `corr_xindex[selected_response] == 0` is necessary as well, if i remember correctly from a discussion with @hnformentin - it's a (work-around) solution for responses with observations

any idea why the check for the index or list was there / why it may now be removed? is the axis just always gonna be an index or a list?

**Comment by hnformentin** [comment]
You are right @valentin-krasontovitsch: `corr_xindex[selected_response] == 0` was a working around. If the user selects a different time step, `corr_xindex` gets updated, so we should not force to have the first observation in this case.

I kept the check `isinstance(x_axis, (pd.Index, list)` because I did not know if this is always the case. If it is not always the case, we need to deal with exceptions. In case we want to remove this condition, I think we should raise an exception inside `_update_corr_index_dict` and test it.

**Comment by valentin-krasontovitsch** [comment]
I was actually gonna fix it in a different way, in `update_corr_index` - i think the source of the bug ultimately lies there. gonna submit my fix, and then we can discuss : )

**Comment by DanSava** [comment]
> In case we want to remove this condition, I think we should raise an exception inside _update_corr_index_dict and test it.

There are already checks inside `_update_corr_index_dict` for both (pd.Index, list) types, that might require a bit of refactoring. Also, I don't think we should throw an exception in this case but just return 0.

**Comment by valentin-krasontovitsch** [comment]
OK after looking a bit more, i have finally come to the conclusion that i am confused : D

i see that we have the callback function `update_corr_index` that has the `correlation-store-xindex` as output, and we have the function `_update_corr_index_dict` that modifies the index for responses with observations.

would it be preferrable if we could integrate the latter into the former? only have one place where whe index is manipulated? @DanSava @hnformentin

**Comment by valentin-krasontovitsch** [comment]
also since I think you worked with storage and how different things are stored - how do you feel about making the `correlation-store-xindex` of session storage type, @DanSava? it helps with reloading the page while responses are chosen, otherwise the callback has to be written in such a way that it populates the whole dictionary on first call, if selected responses exist

... should i create a seperate issue for this? :innocent:

**Comment by hnformentin** [comment]
> OK after looking a bit more, i have finally come to the conclusion that i am confused : D
> 
> i see that we have the callback function `update_corr_index` that has the `correlation-store-xindex` as output, and we have the function `_update_corr_index_dict` that modifies the index for responses with observations.
> 
> would it be preferrable if we could integrate the latter into the former? only have one place where whe index is manipulated? @DanSava @hnformentin

I think that would be great @valentin-krasontovitsch 👏

**Comment by hnformentin** [comment]
> another question - given one response RESP, and ensembles ENS1, ENS2, is it possible that:
> 
> * RESP has different x-axis in ENS1 and ENS2
> * RESP has observations in ENS1 but not in ENS2
> * RESP has a different set of observations each in ENS1 and ENS2 ?
> 
> sorry if the questions potentially don't make sense, i really have no good understanding yet of all the different possible use cases (based on the explanation you gave recently, @hnformentin, I would guess that observations remain constant between ensembles, as does the x-axis, for one fixed, given response)

As I see, the answer for the three questions is "No". Your reasoning is correct 🤓

**Comment by valentin-krasontovitsch** [comment]
great thank you for answering ^^
