### ISSUE TITLE
Legend of response in the observation selector not complete

### ISSUE THREAD

**Issue by hnformentin** [equinor/webviz-ert#347]
**Describe the bug**
See selections in the screenshot. I would expect that the name of the response in the legend of the observation selector was the same as the one in the response selector. In the screenshot below, "SNAKE_OIL_" is being omitted.

**Screenshots**
<img width="1849" alt="Screenshot 2022-08-01 at 13 07 15" src="https://user-images.githubusercontent.com/62240435/182145558-e354a8e9-78c5-43dd-920b-896e6a8d0c13.png">

**Comment by DanSava** [comment]
We can force the names in the legend to be the same but there are instances where the observation name is not the same as the response name as in the case from the issue description
