### ISSUE TITLE
Restrict number of observations displayed in the observation selector

### ISSUE THREAD

**Issue by hnformentin** [equinor/webviz-ert#350]
One of the characteristics of the observation selector defined in #285 was to restrict the number of observations displayed. This was proposed to control loading time. Currently the observation selector has no limitation and does take time to load large number of observations.

**Expected behavior**
The number of observations displayed should be limited to a reasonable number.

**Comment by DanSava** [comment]
Not trivial to guess what a reasonable number might be. Also not very specific on how to limit the observations for example:

We have 1000 observations in a range of 10 years and we want to limit the user to select a maximum of 100 observations, we can:
1) only select the first 100 from the range
2) select the last 100 from the range
3) select 100 observations that are equally spaced in the rage

I suggest postponing the restriction until we get feedback on performance if we will, and make a decision at that time on how to proceed

**Comment by DanSava** [comment]
#384 improves the performance for responses with 100s of observations. For now restricting the number of observations does not seem needed. 

Will close for now and reopen the issue if needed
