### ISSUE TITLE
Plot viewer: x-axis range is wrongly extended to the past

### ISSUE THREAD

**Issue by hnformentin** [equinor/webviz-ert#376]
**Describe the bug**
In the plot viewer of webviz-ert, the range of x-axis is extended back when plotting the `pred_ref` case. We compared to `ert gui` and this behavior is not present there (see images).

**To Reproduce**
1. Get a copy of the data set of Drogon tutorial (tar xhf /scratch/fmu/share/drogon/course/drogon_current.tar.gz)
2. source /prog/res/komodo/stable/enable
3. cd drogon_20211115_12-12/resmod/ff/21.0.1/ert/model
4. ert gui drogon_ahm.ert
5. Select data as indicated in the image

**Expected behavior**
The x-axis should not be displaced to an early date because the case `pred_ref` is loaded.

**Screenshots**
Webviz-ert compared to ert gui:

![Screenshot from 2022-08-18 14-38-46](https://user-images.githubusercontent.com/62240435/185398102-2ffc0f92-c03c-48cb-a382-926ce28580f6.png)

![Screenshot from 2022-08-18 14-34-26](https://user-images.githubusercontent.com/62240435/185398259-ab2525af-d9f7-49f2-a791-765162f85ad8.png)

**Comment by hnformentin** [comment]
By the way, why the color of the observations is different?

**Comment by valentin-krasontovitsch** [comment]
> By the way, why the color of the observations is different?

you mean black in the ert gui, and red in webviz-ert?

**Comment by hnformentin** [comment]
> > By the way, why the color of the observations is different?
> 
> you mean black in the ert gui, and red in webviz-ert?

Yes...

**Comment by valentin-krasontovitsch** [comment]
that's a good question :sweat_smile:

**Comment by hnformentin** [comment]
I noticed the difference, because red–green color blindness is the most common form, so I would avoid having both in the same plot...

**Comment by valentin-krasontovitsch** [comment]
it's a good point! i know way too little about barrier-free design (is that the right term?), and also think about it too litte.

**Comment by andreas-el** [comment]
The issue seems to be caused by a negative value (-1) present in the timestamp series. This is plotted differently in webviz and the gui plotter, where webviz allows this as a valid datapoint and the gui plotter omits drawing it.

**Comment by DanSava** [comment]
Tested this with the latest `drogon_20240807_12_21` and the issue is no longer present. 

![image](https://github.com/user-attachments/assets/933ad9f1-10e0-4377-a09b-dbe1b76418fc)
