### ISSUE TITLE
Parameter histograms not loaded in both webviz-ert and ert gui

### ISSUE THREAD

**Issue by hnformentin** [equinor/webviz-ert#380]
**Describe the bug**
Testing gui and webviz-ert with data from Drogon tutorial, it comes up that the parameter plots are not displayed. It seems that the data is not loaded for some reason. This behavior was observed in webviz-ert and ert gui, but not in webviz.

**To Reproduce**
1. Get a copy of the data set of Drogon tutorial (tar xhf /scratch/fmu/share/drogon/course/drogon_current.tar.gz)
2. source /prog/res/komodo/stable/enable
3. cd drogon_20211115_12-12/resmod/ff/21.0.1/ert/model
4. ert gui drogon_ahm.ert
5. Select data as indicated in the image

**Expected behavior**
I would expect that the data is displayed in ert gui and webviz ert, the same way as it is in webviz.

**Screenshots**

- ert gui and webviz
![Screenshot from 2022-08-19 07-39-37](https://user-images.githubusercontent.com/62240435/185552242-c67ad810-4606-4bb6-a720-c5a95d74d919.png)

- webviz-ert, note that there are many warning messages in the terminal on the left that may be related
![Screenshot from 2022-08-19 07-47-08](https://user-images.githubusercontent.com/62240435/185552192-dd02a177-4243-466b-8a02-088ffa49078c.png)

Nevertheless, with another response the histogram is displayed.
![Screenshot from 2022-08-19 07-57-31](https://user-images.githubusercontent.com/62240435/185552963-3fe1cba6-ca17-4094-b274-3c2b1913b776.png)

**Comment by hnformentin** [comment]
The error message (`** Warning:: invalid node found at offset..`) reminded @oyvindeide about an issue related to incompatibility between storage and config. His suggestion was to check that the steps to reproduce the issue reproduce the error message. After, try to check if the same happens in an earlier komodo version, say from the beginning of this year. With that we could identify if this was a regression...

**Comment by mortalisk** [comment]
I have found the error message first appears in komodo 2022.05

**Comment by mortalisk** [comment]
But other than the printed error message, I don't know if there are any other differences. The issue about missing data seems to be expected as there is no data in the "default" ensemble. I'll check a bit more.

**Comment by mortalisk** [comment]
I also get this: "[WARNING] res.enkf_fs: Index out of bounds. keyword_index=0 vector_size=0"
This happens when fetching from the cases with prefix "pred_"

The other error happens on the "default_" cases.

It seems that the storage in the drogon link in this issue is somwhat corrupted. @oysteoh should we report this somewhere?

**Comment by oysteoh** [comment]
I'm not sure - maybe someone with a better understanding of this could chime in? @berland  do you have any idea what this warning is about and is it something wrong with the dataset or is this a bug introduced in our code?

**Comment by berland** [comment]
Nothing springs to mind 🤷🏻

**Comment by berland** [comment]
This is a new ERT version extracting data from storage as it was in the tar.gz file? Has it been tested to regenerate the storage data for the Drogon case in a newer ERT version?

**Comment by hnformentin** [comment]
I run the case `drogon_ahm.ert`, komodo (2022.08.02-py38), on the August 22th. 
When I try to open it in webviz-ert, it presents a similar warning `2022-08-30 14:21:59,032 [WARNING] res.enkf_fs: Index out of bounds. keyword_index=2 vector_size=0`.
Unless I did something wrong with the way I simulated, it seems the problem persists...

**Comment by hnformentin** [comment]
The initial issue is now outdated.
 https://github.com/equinor/ert/issues/3845 should be investigated instead, it is specific issue for invalid node.
