### ISSUE TITLE
`before_first_request` is deprecated and is to be removed

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#397]
Running the tests in webviz causing this to happen

```
tests/views/test_state_saving.py: 2 warnings
  /prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/flask/scaffold.py:50: DeprecationWarning:
  
  'before_first_request' is deprecated and will be removed in Flask 2.3. Run setup code while creating the application instead.
```
and
```
tests/data/spe1_st/tests/test_webviz_ert.py::test_webviz_observation_analyzer
  /prog/res/komodo/bleeding-py38-rhel7/root/lib/python3.8/site-packages/flask/scaffold.py:50: DeprecationWarning:
  
  'before_first_request' is deprecated and will be removed in Flask 2.3. Run setup code while creating the application instead.
```

I'm not sure where this deprecation warning is raised from, it could be in the dash-framework and that there is nothing we can do but wait for them to patch. But - it should be looked into at least to make sure we are not the problem here.

**Comment by oysteoh** [comment]
@valentin-krasontovitsch could you as our next release manager just verify / check if this is now solved in dash? I guess it is not very far into the future before we go to flask 2.3 and this will break if not fixed.

**Comment by valentin-krasontovitsch** [comment]
fixed in dash 2.7.0 according to [changelog](https://github.com/plotly/dash/blob/dev/CHANGELOG.md#fixed-3)

**Comment by valentin-krasontovitsch** [comment]
should i specify the min version in webviz-ert's requirements? or should i just make sure that bleeding / my current beta komodo build have a higher version? where do we fix this stuff, locally on the project level or globally in komodo or both, and it depends?

**Comment by valentin-krasontovitsch** [comment]
( fyi bleeding has dash 2.7.0 but please still answer the question above if you will ^^ )

**Comment by oysteoh** [comment]
I think just bumping in bleeding and your release is sufficient! Usually we try to have as little pinning / restrictions on the project level as possible.

**Comment by valentin-krasontovitsch** [comment]
perfect, thanks! then i guess this issue can be closed?
