### ISSUE TITLE
Create Observation Analyzer Viewer

### ISSUE THREAD

**Issue by xjules** [equinor/webviz-ert#54]
Design a view that should server as an exploration / analyzer for observation related data: misfits, inactive and active observations. Additionally, it can serve as a workbench for manual (user defined) transformations applied on observations: scaling, deactivating.

**Comment by eivindsm** [comment]
There are a couple of relevant plots ides around. The old webviz has one version. Nybwiz contain some relevant ideas : https://wiki.equinor.com/wiki/index.php/User:Rnyb/nybviz_main

And I have a jupyter-notebook solution from which I attach this screen shot:
![observation_plot](https://user-images.githubusercontent.com/41294438/99786948-685f7900-2b1f-11eb-811a-54764a65894b.PNG)
