### ISSUE TITLE
Displaying metadata on observations

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#61]
Displaying metadata such as values, dates, comments eventually by hovering over observation points.

**Comment by oysteoh** [comment]
There is a separate table for adding metadata. We should look into and make sure that data is exposed through the api - and then eventually show these data when hoovering.

**Comment by dotfloat** [comment]
The API call is (or should be) `GET /observations/{id}/attributes`, which should return key-values of `str: str`.
