### ISSUE TITLE
We need to keep track of and store the relations between ensembles in ERT

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#75]

**Comment by oysteoh** [comment]
Currently we are only persisting relations between iterations in the same run. Restarts will not persist the relation to where it comes from, it will only start a new set of ensembles. Needs to be discussed with the owls - how to determine parenthood? @sondreso

**Comment by oysteoh** [comment]
This needs to be picked up at a later stage as there is no concept of this today in the code and there will not be in near future. For now - we will only make the relations based on the same run of ERT.

**Comment by dotfloat** [comment]
Is this something that we expect to be implemented with the new ensemble evaluator or do we want this in the current libres?

**Comment by oysteoh** [comment]
Not sure, but it will be a concept we introduce in ERT3 - it will not happen in current ERT.

**Comment by dotfloat** [comment]
In that case I think this issue can be closed as not webviz-ert's problem. Neither new storage or webviz care about how the links are created, only that they exist. So then when ERT3 is a thing, this issue will be solved automatically.
