### ISSUE TITLE
Observations seems to be persisted between different responses when navigating back and forth

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#77]
Seems to happen sometimes when switching back and forth. Needs to be investigated.

**Comment by oysteoh** [comment]
We need to reproduce in order to debug this. Ask eivind for more information / if the issue is still there

**Comment by oysteoh** [comment]
@dotfloat has rewritten the api to fast-api, and he claims there is no caching serverside.

**Comment by dotfloat** [comment]
That is, no caching on ERT Storage API. There could be serverside caching from Webviz. This caching could also just be due to global state from our implementation of webviz-ert, either because of webviz or Flask.

**Comment by oysteoh** [comment]
Seems to be a bug in plotly. Maybe related to this https://github.com/plotly/plotly.js/issues/4954 
For now we can use another component, which might not have the same performance - but that needs to be addressed later if there is a need.
