### ISSUE TITLE
Make use of assisted-history-matching-parameters-update-vs-observations from webviz subsurface

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#86]
https://webviz-subsurface-example.azurewebsites.net/assisted-history-matching-parameters-update-vs-observations

**Comment by mortalisk** [comment]
Link does not work. Do you have an updated link/more information?

**Comment by oysteoh** [comment]
I think we'll just leave it. This was one of the pages containing data eivind maybe wanted us to show at some point. It was never prioritized and now we have a new product owner with new prioritizations so i guess we can close this issue.
